name: Test and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      # Step 2: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 3: Run tests and generate coverage report
      - name: Run tests and generate coverage report
        id: test
        run: |
          go test -coverprofile=coverage.out ./...
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      # Step 4: Generate badge
      - name: Update README.MD
        run: |
          # Extract coverage value (remove the % symbol if present)
          COVERAGE=$(echo "${{ env.COVERAGE }}" | tr -d '%')
          
          # First, remove all existing coverage badges to prevent duplicates
          sed -i '/<img.*Coverage.*>/d' README.MD
          
          # Add the coverage badge after the last-commit badge using shields.io URL directly
          sed -i "/<img.*last-commit.*>/a\  <img src=\"https://img.shields.io/badge/Coverage-${COVERAGE}%25-2691fb?style=plastic&logo=none&logoColor=white&labelColor=555555&borderRadius=10\" alt=\"coverage\">" README.MD

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.MD
          git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
